### ISSUE TITLE
Is there an article about this code?

### ISSUE THREAD

**Issue by ULTRAMAN-TIGA-SKY** [saugat76/UAV_SubBand_Allocation_DQN#1]
I wantto learn your code, but I haven't seen the relevant article of this code.
Could you please share it with me? Thank you very much

**Comment by saugat76** [comment]
Hello,

Thank you for reaching out. However there are a lot of bugs in the code
which have not been fixed yet as well as there are other algorithmic
issues. We should be done in about a month and I can give our article to
follow afterwards.

Regards,
Saugat

**Comment by saugat76** [comment]
Hello, here is the link to the complete report you are looking for https://rave.ohiolink.edu/etdc/view?acc_num=miami1688867280874635. The project is a part of a thesis. If you have any queries or suggestions please feel free  to reach out.
