### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by 1219-wangjindong** [saugat76/UAV_SubBand_Allocation_DQN#2]
I wantto learn your code, but I haven't seen the relevant article of this code.
Could you please share it with me? Thank you very much

**Comment by saugat76** [comment]
Hello. Thank you for reaching out. The tensorflow still has some serious flaws so I would suggest you to check our pytorch implementation which is available in our public repo. In addition, the article following this code is currently awaiting acceptance and the preprint should be available is few weeks. I would link it once it is available on this feed.

**Comment by saugat76** [comment]
https://github.com/saugat76/UAV_Subband_Allocation_DQN_Pytorch

**Comment by saugat76** [comment]
Hello, here is the link to the complete report you are looking for https://rave.ohiolink.edu/etdc/view?acc_num=miami1688867280874635. The project is a part of a thesis. If you have any queries or suggestions please feel free  to reach out.
